# Generated by Django 4.2.3 on 2023-08-16 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_postcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcomment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
