# Generated by Django 4.2.3 on 2023-08-17 06:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0009_alter_banner_content_alter_banner_heading_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='postcomment',
            unique_together={('post', 'comment', 'user')},
        ),
    ]
