# Generated by Django 4.2.3 on 2023-08-17 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_pollpostrespond'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollpost',
            name='respond_count',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
