# Generated by Django 4.2.3 on 2023-08-17 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_pollpost_respond_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollpost',
            name='respond_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='pollpostrespond',
            constraint=models.UniqueConstraint(fields=('user', 'post_poll'), name='unique_user_poll_response'),
        ),
    ]
