# Generated by Django 4.2.3 on 2023-08-18 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_alter_pollpost_respond_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='heading',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
