# Generated by Django 4.2.3 on 2023-07-13 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(upload_to='profiles')),
                ('about', models.TextField()),
                ('personal_website', models.CharField(max_length=200)),
                ('communication_cord', models.BooleanField(default=False)),
                ('tech_cord', models.BooleanField(default=False)),
                ('following_count', models.PositiveIntegerField()),
                ('followers_count', models.PositiveIntegerField()),
                ('is_profile_completed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
