# Generated by Django 4.2.3 on 2023-07-13 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_userprofile_batch_alter_userprofile_hub'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='badges',
            options={'verbose_name_plural': 'Badges'},
        ),
        migrations.AlterModelOptions(
            name='batch',
            options={'verbose_name_plural': 'batches'},
        ),
        migrations.AlterField(
            model_name='batch',
            name='number',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='hub',
            name='code',
            field=models.CharField(max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='hub',
            name='location',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
