# Generated by Django 4.2.3 on 2023-07-15 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_user_is_block'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectedMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='connected_media',
            field=models.ManyToManyField(to='accounts.connectedmedia'),
        ),
    ]
