# Generated by Django 4.2.3 on 2023-07-16 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_loginwithemaildata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginwithemaildata',
            name='user',
        ),
    ]
