# Generated by Django 4.2.3 on 2023-07-16 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_loginwithemaildata_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginwithemaildata',
            name='email',
            field=models.CharField(default='not given', max_length=50),
        ),
    ]
