# Generated by Django 4.2.3 on 2023-07-17 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_loginwithemaildata_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='number',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
