# Generated by Django 4.2.3 on 2023-07-17 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_batch_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('icon', models.ImageField(null=True, upload_to='stack-icons')),
            ],
        ),
        migrations.AlterField(
            model_name='badges',
            name='badge_icon',
            field=models.ImageField(upload_to='badge-icons'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='stack',
            field=models.ManyToManyField(to='accounts.stack'),
        ),
    ]
