# Generated by Django 4.2.3 on 2023-07-17 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_remove_userprofile_stack_userprofile_stack'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ConnectedMedia',
            new_name='ConnectedSocialMedia',
        ),
        migrations.AlterField(
            model_name='stack',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='stack-icons'),
        ),
    ]
