# Generated by Django 4.2.3 on 2023-07-21 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_skill_socialmedia_project_follow_userprofile_skills_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='connected_media',
        ),
        migrations.DeleteModel(
            name='ConnectedSocialMedia',
        ),
    ]
