# Generated by Django 4.2.3 on 2023-07-21 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_remove_user_connected_media_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedia',
            name='icon',
            field=models.ImageField(null=True, upload_to='social-media-icons'),
        ),
    ]
