# Generated by Django 4.2.3 on 2023-07-23 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_alter_socialmedia_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='badges',
            old_name='badge_desc',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='badges',
            old_name='badge_icon',
            new_name='icon',
        ),
        migrations.RenameField(
            model_name='badges',
            old_name='badge_name',
            new_name='name',
        ),
    ]
