# Generated by Django 4.2.3 on 2023-07-24 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_alter_userprofile_badges_alter_userprofile_hub_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='live_link',
            field=models.CharField(max_length=50),
        ),
    ]
