# Generated by Django 4.2.3 on 2023-07-24 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_alter_project_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='social_media',
        ),
        migrations.CreateModel(
            name='UserSocialMediaAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=80)),
                ('social_media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.socialmedia')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
