# Generated by Django 4.2.3 on 2023-07-27 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_userprofile_is_profile_completed_alter_user_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_profile_completed',
        ),
    ]
