# Generated by Django 4.2.3 on 2023-07-28 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_remove_userprofile_is_profile_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedia',
            name='icon',
            field=models.ImageField(upload_to='social-media-icons'),
        ),
    ]
