# Generated by Django 4.2.3 on 2023-07-30 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_remove_skill_color_alter_socialmedia_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usereducation',
            name='course',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='icon',
            field=models.ImageField(blank=True, upload_to='', verbose_name='skill-icons'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
