# Generated by Django 4.2.3 on 2023-08-07 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_dos_donts'),
    ]

    operations = [
        migrations.AddField(
            model_name='donts',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dos',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
