# Generated by Django 4.2.3 on 2023-08-08 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0046_rename_donts_donts_dont'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usersocialmediaaccounts',
            unique_together={('social_media', 'user')},
        ),
    ]
