# Generated by Django 4.2.3 on 2023-08-09 04:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0047_alter_usersocialmediaaccounts_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersocialmediaaccounts',
            name='social_media',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.socialmedia'),
        ),
        migrations.AlterField(
            model_name='usersocialmediaaccounts',
            name='url',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='usersocialmediaaccounts',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ProjectAdditionalSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=50)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.project')),
            ],
        ),
    ]
