# Generated by Django 4.2.3 on 2023-08-16 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0051_emailchangeotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailchangeotp',
            name='new_email',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
