# Generated by Django 4.2.3 on 2023-08-16 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0052_emailchangeotp_new_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailchangeotp',
            name='time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
